<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<div id="bottom">
		<div id="link">
			<a href="page/html/company.php" target="_self">关于我们</a> | 
			<a href="page/contact/contact.php" target="_self">联系方式</a> | 
			<a href="page/contact/feedback.php" target="_self">在线留言</a> | 
			<a href="advs/link/" target="_self">友情链接</a>
		</div>
		<div id="copyright">
			版权所有 Copyright(C)2009-2010 杭州某某手机配件公司
		</div>
	</div>