<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<ul id="menu">
	<li><a href="./SortServlet?action=newsAdd">添加新闻</a></li>  
	<li><a href="./NewsServlet?action=selectAll">新闻管理</a></li> 
	
	<li><a href="./SortServlet?action=selectAll">分类管理</a></li> 
    
	<li><a href="./UserServlet?action=selectAll">用户管理</a></li>
    <li style="float:right;padding-right: 0;"><a href="">退出</a></li>
    <li style="float:right;"><a href="">密码更改</a></li>
  <li style="float:right;"></li>  
    
</ul>